services:
  _defaults:
    autowire: true
    autoconfigure: true

  Bedrock\Bundle\RateLimitBundle\:
    resource: '../../../src/*'

  Bedrock\Bundle\RateLimitBundle\EventListener\ReadRateLimitAttributeListener:
    arguments:
      $limit: '%bedrock_rate_limit.limit%'
      $period: '%bedrock_rate_limit.period%'
      $limitByRoute: '%bedrock_rate_limit.limit_by_route%'
      $rateLimitModifiers: !tagged rate_limit.modifiers

  Bedrock\Bundle\RateLimitBundle\EventListener\ReadRateLimitConfigurationListener:
    arguments:
      $limit: '%bedrock_rate_limit.limit%'
      $period: '%bedrock_rate_limit.period%'
      $rateLimitModifiers: !tagged rate_limit.modifiers
      $routes: '%bedrock_rate_limit.routes%'

  Bedrock\Bundle\RateLimitBundle\EventListener\ReadGraphQLRateLimitAttributeListener:
    arguments:
      $limit: '%bedrock_rate_limit.limit%'
      $period: '%bedrock_rate_limit.period%'
      $rateLimitModifiers: !tagged rate_limit.modifiers

  Bedrock\Bundle\RateLimitBundle\EventListener\LimitRateListener:
    arguments:
      $displayHeaders: '%bedrock_rate_limit.display_headers%'

  Bedrock\Bundle\RateLimitBundle\EventListener\AddRateLimitHeadersListener:
    arguments:
      $displayHeaders: '%bedrock_rate_limit.display_headers%'
