services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
        Symfony\Component\DependencyInjection\ContainerInterface $container: '@service_container'
        int $limit: '%bedrock_rate_limit.limit%'
        int $period: '%bedrock_rate_limit.period%'
        array $routes: '%bedrock_rate_limit.routes%'
        bool $limitByRoute: '%bedrock_rate_limit.limit_by_route%'
        bool $displayHeaders: '%bedrock_rate_limit.display_headers%'
        iterable $rateLimitModifiers: !tagged rate_limit.modifiers

  Bedrock\Bundle\RateLimitBundle\:
    resource: '../../../src/*'
