name: Continuous Integration
on: [pull_request]

jobs:
    ci:
        name: Tests & Quality
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
            - run: make install
            - run: make ci
