name: Continuous Integration
on: [pull_request]

jobs:
    ci:
        name: Tests & Quality
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: [ '8.0', '8.1' ]
            fail-fast: false
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.version }}
            - run: make install
            - run: make ci
