name: Continuous Integration
on: [pull_request]

jobs:
    ci:
        name: Tests & Quality
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ '8.0', '8.1' ]
                symfony-version: ['^5.4', '^6.0']
            fail-fast: false
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - run: composer require symfony/symfony:${{ matrix.symfony-version }} --no-update
            - run: make install
            - run: make ci
